load("cuda/9.0")
setenv("MAPD_USER",os.getenv("USER"))
setenv("MAPD_GROUP","g-srinivm")
setenv("MAPD_STORAGE","/home/srinivm/.mapd/mapd")
setenv("MAPD_PATH","/home/srinivm/CentOS7/software/mapd/3.4.0-gpu")
mapd_path=os.getenv("MAPD_PATH")
prepend_path("PATH",tostring(mapd_path))
